apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c-template-test
  janus-idp.io/tekton: c-template-test
  backstage.io/kubernetes-id: c-template-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c-template-test
resources:
- deployment.yaml
- route.yaml
- service.yaml
