apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c-template-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c-template-test 
  name: c-template-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c-template-test 
